# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'oc_teacher_phone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for DelayApp
  pod 'MJRefresh', '~> 3.1.15'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Toast', '~> 3.1.0'
  pod 'FMDB'
end
